namespace FullBasic.Lexer;

/// <summary>
/// Reserved-word table. Per ISO 10279 keywords are case-insensitive; we lower-case
/// before lookup so the source case is preserved on the Token's Text field.
/// </summary>
internal static class Keywords
{
    private static readonly Dictionary<string, TokenKind> _table = BuildTable();

    public static bool TryLookup(ReadOnlySpan<char> identifier, out TokenKind kind)
    {
        // Case-insensitive lookup. We avoid allocating a lower-case copy for the
        // common identifier case by using a dedicated comparer.
        var name = identifier.ToString();
        return _table.TryGetValue(name, out kind);
    }

    private static Dictionary<string, TokenKind> BuildTable()
    {
        var t = new Dictionary<string, TokenKind>(StringComparer.OrdinalIgnoreCase)
        {
            // Word-form operators
            ["AND"] = TokenKind.KwAnd,
            ["BAND"] = TokenKind.KwBand,
            ["BNOT"] = TokenKind.KwBnot,
            ["BOR"] = TokenKind.KwBor,
            ["BXOR"] = TokenKind.KwBxor,
            ["EQV"] = TokenKind.KwEqv,
            ["IMP"] = TokenKind.KwImp,
            ["MOD"] = TokenKind.KwMod,
            ["NOT"] = TokenKind.KwNot,
            ["OR"] = TokenKind.KwOr,
            ["REMAINDER"] = TokenKind.KwRemainder,
            ["XOR"] = TokenKind.KwXor,

            // Statement / structural keywords
            ["ACCESS"] = TokenKind.KwAccess,
            ["AS"] = TokenKind.KwAs,
            ["ASK"] = TokenKind.KwAsk,
            ["AT"] = TokenKind.KwAt,
            ["BASE"] = TokenKind.KwBase,
            ["BEGIN"] = TokenKind.KwBegin,
            ["BREAK"] = TokenKind.KwBreak,
            ["BY"] = TokenKind.KwBy,
            ["CALL"] = TokenKind.KwCall,
            ["CASE"] = TokenKind.KwCase,
            ["CAUSE"] = TokenKind.KwCause,
            ["CHAIN"] = TokenKind.KwChain,
            ["CLEAR"] = TokenKind.KwClear,
            ["CLIP"] = TokenKind.KwClip,
            ["CLOSE"] = TokenKind.KwClose,
            ["COLLATE"] = TokenKind.KwCollate,
            ["CON"] = TokenKind.KwCon,
            ["CONDITION"] = TokenKind.KwCondition,
            ["CONTINUE"] = TokenKind.KwContinue,
            ["COPY"] = TokenKind.KwCopy,
            ["DATA"] = TokenKind.KwData,
            ["DECLARE"] = TokenKind.KwDeclare,
            ["DEF"] = TokenKind.KwDef,
            ["DELETE"] = TokenKind.KwDelete,
            ["DIM"] = TokenKind.KwDim,
            ["DISPLAY"] = TokenKind.KwDisplay,
            ["DO"] = TokenKind.KwDo,
            ["DRAW"] = TokenKind.KwDraw,
            ["ELSE"] = TokenKind.KwElse,
            ["ELSEIF"] = TokenKind.KwElseif,
            ["END"] = TokenKind.KwEnd,
            ["ERASE"] = TokenKind.KwErase,
            ["ERROR"] = TokenKind.KwError,
            ["EXCEPTION"] = TokenKind.KwException,
            ["EXIT"] = TokenKind.KwExit,
            ["EXTERNAL"] = TokenKind.KwExternal,
            ["FILE"] = TokenKind.KwFile,
            ["FILES"] = TokenKind.KwFiles,
            ["FILETYPE"] = TokenKind.KwFiletype,
            ["FIXED"] = TokenKind.KwFixed,
            ["FN"] = TokenKind.KwFn,
            ["FOR"] = TokenKind.KwFor,
            ["FORMAT"] = TokenKind.KwFormat,
            ["FUNCTION"] = TokenKind.KwFunction,
            ["GO"] = TokenKind.KwGo,
            ["GOSUB"] = TokenKind.KwGosub,
            ["GOTO"] = TokenKind.KwGoto,
            ["GRAPH"] = TokenKind.KwGraph,
            ["HANDLER"] = TokenKind.KwHandler,
            ["IDN"] = TokenKind.KwIdn,
            ["IF"] = TokenKind.KwIf,
            ["IMAGE"] = TokenKind.KwImage,
            ["IN"] = TokenKind.KwIn,
            ["INPUT"] = TokenKind.KwInput,
            ["INTERNAL"] = TokenKind.KwInternal,
            ["INV"] = TokenKind.KwInv,
            ["IS"] = TokenKind.KwIs,
            ["KEY"] = TokenKind.KwKey,
            ["LET"] = TokenKind.KwLet,
            ["LINE"] = TokenKind.KwLine,
            ["LINES"] = TokenKind.KwLines,
            ["LOCAL"] = TokenKind.KwLocal,
            ["LOOP"] = TokenKind.KwLoop,
            ["MARGIN"] = TokenKind.KwMargin,
            ["MASK"] = TokenKind.KwMask,
            ["MAT"] = TokenKind.KwMat,
            ["MISSING"] = TokenKind.KwMissing,
            ["MIX"] = TokenKind.KwMix,
            ["MIXED"] = TokenKind.KwMixed,
            ["MODULE"] = TokenKind.KwModule,
            ["NAME"] = TokenKind.KwName,
            ["NATIVE"] = TokenKind.KwNative,
            ["NEXT"] = TokenKind.KwNext,
            ["NEW"] = TokenKind.KwNew,
            ["NO"] = TokenKind.KwNo,
            ["NONE"] = TokenKind.KwNone,
            ["NUL"] = TokenKind.KwNul,
            ["NUMERIC"] = TokenKind.KwNumeric,
            ["OF"] = TokenKind.KwOf,
            ["OFF"] = TokenKind.KwOff,
            ["ON"] = TokenKind.KwOn,
            ["OPEN"] = TokenKind.KwOpen,
            ["OPTION"] = TokenKind.KwOption,
            ["ORGANIZATION"] = TokenKind.KwOrganization,
            ["OUT"] = TokenKind.KwOut,
            ["OUTIN"] = TokenKind.KwOutin,
            ["OUTPUT"] = TokenKind.KwOutput,
            ["PARALLEL"] = TokenKind.KwParallel,
            ["PIC"] = TokenKind.KwPic,
            ["PICTURE"] = TokenKind.KwPicture,
            ["PLOT"] = TokenKind.KwPlot,
            ["POINT"] = TokenKind.KwPoint,
            ["POINTS"] = TokenKind.KwPoints,
            ["POINTER"] = TokenKind.KwPointer,
            ["POLYGON"] = TokenKind.KwPolygon,
            ["PRINT"] = TokenKind.KwPrint,
            ["PRIVATE"] = TokenKind.KwPrivate,
            ["PROGRAM"] = TokenKind.KwProgram,
            ["PROMPT"] = TokenKind.KwPrompt,
            ["PUBLIC"] = TokenKind.KwPublic,
            ["RANDOMIZE"] = TokenKind.KwRandomize,
            ["READ"] = TokenKind.KwRead,
            ["REAL"] = TokenKind.KwReal,
            ["RECORD"] = TokenKind.KwRecord,
            ["RECSIZE"] = TokenKind.KwRecsize,
            ["RECTYPE"] = TokenKind.KwRectype,
            ["REDIM"] = TokenKind.KwRedim,
            ["RELATIVE"] = TokenKind.KwRelative,
            ["REM"] = TokenKind.KwRem,
            ["REPEAT"] = TokenKind.KwRepeat,
            ["REST"] = TokenKind.KwRest,
            ["RESTORE"] = TokenKind.KwRestore,
            ["RESET"] = TokenKind.KwReset,
            ["RETRY"] = TokenKind.KwRetry,
            ["RETURN"] = TokenKind.KwReturn,
            ["REWRITE"] = TokenKind.KwRewrite,
            ["RUN"] = TokenKind.KwRun,
            // ROUND is a function name (handled by Sema/Builtins), not a keyword.
            ["RSET"] = TokenKind.KwRset,
            ["SAME"] = TokenKind.KwSame,
            ["SELECT"] = TokenKind.KwSelect,
            ["SEQUENTIAL"] = TokenKind.KwSequential,
            ["SET"] = TokenKind.KwSet,
            ["SHARE"] = TokenKind.KwShare,
            ["SIZE"] = TokenKind.KwSize,
            ["SKIP"] = TokenKind.KwSkip,
            ["SOUND"] = TokenKind.KwSound,
            ["STANDARD"] = TokenKind.KwStandard,
            ["STATUS"] = TokenKind.KwStatus,
            ["STEP"] = TokenKind.KwStep,
            ["STOP"] = TokenKind.KwStop,
            ["STREAM"] = TokenKind.KwStream,
            ["STRING"] = TokenKind.KwString,
            ["SUB"] = TokenKind.KwSub,
            ["SUFFICIENT"] = TokenKind.KwSufficient,
            ["TEMPLATE"] = TokenKind.KwTemplate,
            ["TEXT"] = TokenKind.KwText,
            ["THEN"] = TokenKind.KwThen,
            ["TIMEOUT"] = TokenKind.KwTimeout,
            ["TO"] = TokenKind.KwTo,
            ["TRACE"] = TokenKind.KwTrace,
            ["TRANSFORM"] = TokenKind.KwTransform,
            ["TRN"] = TokenKind.KwTrn,
            // TRUNCATE is a function name (handled by Sema/Builtins), not a keyword.
            ["TYPE"] = TokenKind.KwType,
            ["UNSAVE"] = TokenKind.KwUnsave,
            ["UNTIL"] = TokenKind.KwUntil,
            ["USE"] = TokenKind.KwUse,
            ["USING"] = TokenKind.KwUsing,
            ["VARIABLE"] = TokenKind.KwVariable,
            ["VIEWPORT"] = TokenKind.KwViewport,
            ["WAIT"] = TokenKind.KwWait,
            ["WHEN"] = TokenKind.KwWhen,
            ["WHERE"] = TokenKind.KwWhere,
            ["WHILE"] = TokenKind.KwWhile,
            ["WINDOW"] = TokenKind.KwWindow,
            ["WITH"] = TokenKind.KwWith,
            ["WRITE"] = TokenKind.KwWrite,
            ["ZER"] = TokenKind.KwZer,
            ["ZONEWIDTH"] = TokenKind.KwZonewidth,
        };
        return t;
    }
}
