namespace FullBasic.Lexer;

/// <summary>
/// All token kinds emitted by the lexer for ISO/IEC 10279 Full BASIC. One value
/// per reserved word so the parser can pattern-match on TokenKind directly.
/// Keyword values use the Kw prefix; symbol punctuation/operators use no prefix.
/// </summary>
public enum TokenKind
{
    // -- Layout & special --
    Unknown,
    EndOfFile,
    Newline,

    // -- Literals --
    NumericLiteral,
    StringLiteral,

    // -- Identifiers --
    Identifier,        // FOO, X1, etc.
    StringIdentifier,  // FOO$, X1$
    LineLabel,         // leading integer at start of a logical line

    // -- Punctuation --
    LParen,
    RParen,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    Question,
    Hash,              // #channel-number

    // -- Operators (symbol form) --
    Plus,
    Minus,
    Asterisk,
    Slash,
    Caret,
    Ampersand,         // string concatenation
    Equal,
    NotEqual,          // <>
    Less,
    LessEqual,
    Greater,
    GreaterEqual,

    // -- Reserved words --
    // Word-form operators come first, then everything else alphabetically.
    KwAnd,
    KwBand,
    KwBnot,
    KwBor,
    KwBxor,
    KwEqv,
    KwImp,
    KwMod,
    KwNot,
    KwOr,
    KwRemainder,
    KwXor,

    KwAccess,
    KwAs,
    KwAsk,
    KwAt,
    KwBase,
    KwBegin,
    KwBreak,
    KwBy,
    KwCall,
    KwCase,
    KwCause,
    KwChain,
    KwClear,
    KwClip,
    KwClose,
    KwCollate,
    KwCon,
    KwCondition,
    KwContinue,
    KwCopy,
    KwData,
    KwDeclare,
    KwDef,
    KwDelete,
    KwDim,
    KwDisplay,
    KwDo,
    KwDraw,
    KwElse,
    KwElseif,
    KwEnd,
    KwErase,
    KwError,
    KwException,
    KwExit,
    KwExternal,
    KwFile,
    KwFiles,
    KwFiletype,
    KwFixed,
    KwFn,
    KwFor,
    KwFormat,
    KwFunction,
    KwGo,
    KwGosub,
    KwGoto,
    KwGraph,
    KwHandler,
    KwIdn,
    KwIf,
    KwImage,
    KwIn,
    KwInput,
    KwInternal,
    KwInv,
    KwIs,
    KwKey,
    KwLet,
    KwLine,
    KwLines,
    KwLocal,
    KwLoop,
    KwMargin,
    KwMask,
    KwMat,
    KwMissing,
    KwMix,
    KwMixed,
    KwModule,
    KwName,
    KwNative,
    KwNext,
    KwNew,
    KwNo,
    KwNone,
    KwNul,
    KwNumeric,
    KwOf,
    KwOff,
    KwOn,
    KwOpen,
    KwOption,
    KwOrganization,
    KwOut,
    KwOutin,
    KwOutput,
    KwParallel,
    KwPic,
    KwPicture,
    KwPlot,
    KwPoint,
    KwPoints,
    KwPointer,
    KwPolygon,
    KwPrint,
    KwPrivate,
    KwProgram,
    KwPrompt,
    KwPublic,
    KwRandomize,
    KwRead,
    KwReal,
    KwRecord,
    KwRecsize,
    KwRectype,
    KwRelative,
    KwRem,
    KwRepeat,
    KwRest,
    KwRestore,
    KwReset,
    KwRetry,
    KwReturn,
    KwRewrite,
    KwRound,
    KwRset,
    KwSame,
    KwSelect,
    KwSequential,
    KwSet,
    KwShare,
    KwSize,
    KwSkip,
    KwSound,
    KwStandard,
    KwStatus,
    KwStep,
    KwStop,
    KwStream,
    KwString,
    KwSub,
    KwSufficient,
    KwTemplate,
    KwText,
    KwThen,
    KwTimeout,
    KwTo,
    KwTrace,
    KwTransform,
    KwTrn,
    KwTruncate,
    KwType,
    KwUnsave,
    KwUntil,
    KwUse,
    KwUsing,
    KwVariable,
    KwViewport,
    KwWait,
    KwWhen,
    KwWhere,
    KwWhile,
    KwWindow,
    KwWith,
    KwWrite,
    KwZer,
    KwZonewidth,
}
