<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FullBasic.Core\FullBasic.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Singulink.Numerics.BigDecimal" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFrameworks>net9.0;netstandard2.1</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
